### ISSUE TITLE
Integration with etherscan and web3.js?

### ISSUE THREAD

**Issue by James-Sangalli** [studydefi/money-legos#36]
Hi All,

Love the idea of this repo, has the potential to be super convenient for a lot of web3 developers.

Have you thought about retrieving all the defined contracts from etherscan and feeding them into your library?

This would also make sense as an add on to web3.js because you could fiddle with the known contracts while also having the capacity to call upon them as web3 contract objects.

**Comment by adrianmcli** [comment]
Hey thanks for the issue, but I don't think we're going to be doing that for this repo any time soon.

> retrieving all the defined contracts from etherscan

This is going to be a lot of contracts and we want to stick to specific protocols for now, so grabbing everything from Etherscan might not make much sense.

> add on to web3.js

We want to keep this library as simple as possible for now. There's also a big shift in people moving away from Web3.js towards Ethers.js. We don't want to be prescriptive here, so we refrain from prescribing either or and simply provide the ABIs and addresses for users to choose.

**Comment by James-Sangalli** [comment]
Thanks for the reply!

Would you consider adding an open source licence for this repo?

**Comment by adrianmcli** [comment]
good call, let's do that. I was thinking MIT would work well?

**Comment by James-Sangalli** [comment]
> good call, let's do that. I was thinking MIT would work well?

MIT would be perfect, was hoping you would say that :)

**Comment by adrianmcli** [comment]
Done. I'll be closing the issue for now. Sorry we can't move ahead with your suggestions at this time, but thanks for participating!
