### ISSUE TITLE
Dark and light mode with switch

### ISSUE THREAD

**Issue by boopathikumar018** [studydefi/money-legos#57]
Hi

Let me know if you would like to add [docsify-darklight-theme](https://docsify-darklight-theme.boopathikumar.me/#/) for you docsify documentation. I will give PR

**Comment by adrianmcli** [comment]
I think we will try to stick with our scheme for now. Unfortunately we found that having to manage both light and dark modes on our blog was an additional maintenance burden making sure everything looked good.

Thanks for reaching out though.
