### ISSUE TITLE
Fix Synthetix Test

### ISSUE THREAD

**Issue by adrianmcli** [studydefi/money-legos#65]
@marcelomorgado I prematurely merged your PR into master by accident. I haven't done a release yet because there's still an issue.

One of the Synthetix tests are failing:

<img width="487" alt="Screen Shot 2020-06-23 at 11 46 26 PM" src="https://user-images.githubusercontent.com/943555/85497360-c9ecdd00-b5ab-11ea-97f9-3767d440f3b8.png">

@marcelomorgado Can you fix this and make a new PR?

**Comment by adrianmcli** [comment]
See failing CI here: https://app.circleci.com/pipelines/github/studydefi/money-legos/189/workflows/2d6fc2e6-cda6-42e2-ab29-f3dbcbba9f1c/jobs/323/steps

**Comment by marcelomorgado** [comment]
Sure, I'm working on that now.

**Comment by adrianmcli** [comment]
Thanks!
